# Config message for ClickTpa
# Version v1.5
# Author: jklmao

# # # # # # # # # # # # # # # # # # # # # # # # #
#                                               #
#                ClickTpa Config                #
#                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # 

#           Be aware of all warnings!           #

# # # # # # # # # # # # # # # # # # # # # # # # #
#                                               #
#                 Place Holders                 #
#                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # 

# Use '%player%' for the player who sent the request.
# Use '%accept%' for the 'Click-to-accept' message.
# Use '%deny%' for the 'Click-to-deny' message.
# Use '%target%' for the player who they wanted to teleport to, and for the 'Player-sent-request' message.
# Example: /tpa <player>, where <player> is '%target%'.

Player-only-command: '&cOnly players can use this command!'

Insufficient-permission: '&cYou do not have sufficient permission!'

Player-deny-tpa-message: '&cTeleportation request has been denied.'

Target-deny-tpa-message: '&cTeleportation request has been denied.'

Target-teleportion-canceled: '&cTeleportation canceled...'

Player-got-accepted-tpa: '&bTeleportation request has been accepted.'

Countdown-until-tpa: '&eTeleporting in 3 seconds...'

Player-no-pendingtpa-message: '&cYou do not have a pending request!'

Target-accepted-tpa-request: '&eRequest for teleportation is accepted.'

No-player-found: '&cThis player does not exist!'

Target-is-offline: '&cThat player is currently offline.'

Player-teleporting-self: '&cYou can not teleport yourself!'

Player-already-requested: '&cYou already requested, please wait..'

Player-teleportation-request-expire: '&cTeleportation request has expired.'

Target-teleportation-request-expire: '&cTeleportation request has expired.'

Player-currently-teleporting: '&bTeleporting...'

Target-currently-teleporting: '&eTeleporting...'

Player-TpToggle-Off: '&eTeleportation &6OFF'

Player-TpToggle-On: '&eTeleportation &6ON'

Target-Is-TpToggled: '&6%target% &ehas teleportation off'

Player-Is-TpToggled: '&cYou are tptoggled!'

Tpacancel-message: '&6Tpa request has been canceled.'


# Seconds until tpa
# Please use whole numbers

Seconds-until-tpa: 3


# Becareful in this part!
# This is when a player uses not enough args
# For example, when a player does '/tpa', it will say 'Usage: /tpa <player>'
# So please fit the correct command under the correct message!
# P.S '/tpohere' is also '/s' (essentials-type command).


Tpa-usage: '&cUse: /tpa <player>'

Tpahere-usage: '&cUse: /tpahere <player>'

Tpaccept-usage: '&cUse: /tpaccept <player>'

Tpdeny-usage: '&cUse: /tpadeny <player>'

Tpo-usage: '&cUse: /tpo <player>'

Tpohere-usage: '&cUse: /tpohere <player> or /s <player>' 


# # # # # # # # # # # # # # # # # # # # # # # # #
#                                               #
#                  Please Read!                 #
#                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # 

# This section is when a player gets a tpa request
# Since the code used is broken into many parts, there will be many messages.
# Whatever you do to the "Click-to-x" messages, will be the same in the 'Tpa-message'
# Be careful!


# Lets you choose if you want players to be able
# to move before being teleported
Allow-player-to-move: false

Player-moved-before-tp: '&6The request was canceled because %player% moved!'

Player-sent-request: '&eYou have sent a request to &6%target%'

Tpa-message: 
  - ''
  - '&6%player% &ehas requested to teleport to you.'
  - '&eClick %accept% &eto accept or click %deny% &eto deny.'
  - '&eThe request expires in 120 seconds.'
  - ''

Tpahere-message: 
  - ''
  - '&6%player% &ehas requested to teleport you to them.'
  - '&eClick %accept% &eto accept or click %deny% &eto deny.'
  - '&eThe request expires in 120 seconds.'
  - ''

# This will put additional spaces for the accept/deny messages
Added-accept-deny-space: true

Click-to-accept: '&a&l&n[ACCEPT]&r'
Click-to-deny: '&c&l&n[DENY]&r'

Hover-message-on-accept: '&aClick to accept'
Hover-message-on-deny: '&cClick to deny'


#~~~~~~~~~~~~~~~~~~#
# More Coming Soon!#
#~~~~~~~~~~~~~~~~~~#

